config/routes.rb
JoyCorn::Application.routes.draw do
  root 'static_pages#index'

  devise_for :users
  resources :posts do
    collection do
      get 'view'
    end
  end
  post '/likes' => 'likes#create'
  delete '/likes' => 'likes#destroy'
  match 'page/:id' => 'static_pages#next', via:[:GET]
  get "static_pages/index"
  get "static_pages/help"
  get "static_pages/next"
  get "static_pages/search"

  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  resources :signed_urls, only: :index

  

end

app/views/layouts/_featured_list.html.erb
<ul id="featured-list">
  <% @likes.each do |like| %>
      <% post = like.post %>
      <li class="featured-item">
        <div class="media-container">
          <% if post.media_type == 'image' %>

              <% image = post.images.first %>
              <% unless image.nil? %>
                  <% if image.link.include? "http" %>
                      <% image_src = image.link %>
                  <% else %>
                      <% image_src = image_path(image.link) %>
                  <% end %>
                  <div class="center-cropped"
                       style="background-image: url(<%= image_src %>)">
                  <%# image_tag(image_src)%>
                    <%= link_to image_tag(image_src, alt: "Lightbox Photo"), view_posts_path(:post_id => post.id), class: "lightview" %>
                  </div>
              <% end %>

          <% elsif post.media_type == 'video' %>
              <div class="featured-media-button">
                <%= link_to image_tag('video-icon.png'), view_posts_path(:post_id => post.id), class: "lightview" %>
              </div>
          <% elsif post.media_type == 'audio' %>
              <div class="featured-media-button">
                <%= link_to image_tag('audio-icon.png'), view_posts_path(:post_id => post.id), class: "lightview" %>
              </div>
          <% elsif post.media_type == 'text' %>
              <div class="featured-media-button">
                <%= link_to image_tag('text-icon.png'), view_posts_path(:post_id => post.id), class: "lightview" %>
              </div>
          <% end %>
        </div>
        <div class="info-container">
          <%= post.title unless like.nil? %>
        </div>
      </li>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<%= render 'shared/foot_info' %>

<script>

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46682005-1', 'joycorn.tk');
    ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
  <div id="logo">
    <%= render 'shared/logo' %>
  </div>

  <div id="log-wrap">
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>



  <div id="nav-wrap">
    <ul id="navBar">
      <li class="nav nav-current">
          <!--<a href= "#" onclick="reloadPage()">HOME-->
          <!--</a>-->
        <!--<a href="#" onclick="home_button()">HOME</a>-->
         <%= link_to "HOME", root_url %>
      </li>
      <li class="nav" >
         <%= link_to "HELP", static_pages_help_url %>
      </li>
    </ul>
  </div>

  <div id="search-box">
    <%= render 'shared/search' %>
  </div>

app/views/layouts/_shim.html.erb
<!--[if It IE 9]>
<script
        src = "http://html5shim.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->

app/views/layouts/_sidebar_classification.html.erb
<h4>
  <a href="javascript:showMenu('topics')">
    <!--<%= image_tag("sidebar/sort.png", class:"sidebar-c-icon") %>-->
    TOPICS
  </a>
</h4>
<ul class="sidebarUl" id="topics">
  <li class="sideButton">
    <%= link_to 'default', static_pages_search_path(:search_type => 'topic', :keyword => 'default') %>
  </li>
</ul>

<h4><a href="javascript:showMenu('types')">TYPES</a></h4>
<ul class="sidebarUl" id="types">
  <li class="sideButton">

    <%= link_to 'text', static_pages_search_path(:search_type => 'type', :keyword => 'text') %>
  </li>
  <li class="sideButton">
    <%= link_to 'image', static_pages_search_path(:search_type => 'type', :keyword => 'image') %>
  </li>
  <li class="sideButton">
    <%= link_to 'audio', static_pages_search_path(:search_type => 'type', :keyword => 'audio') %>
  </li>
  <li class="sideButton">
    <%= link_to 'video', static_pages_search_path(:search_type => 'type', :keyword => 'video') %>
  </li>
</ul>


<h4><a href="javascript:showMenu('postTime')">POSTING TIME</a></h4>
<ul class="sidebarUl" id="postTime">
  <li class="sideButton">
    <%= link_to 'in one day', static_pages_search_path(:search_type => 'time', :keyword => 1.day.ago) %>
  </li>
  <li class="sideButton">
    <%= link_to 'in two days', static_pages_search_path(:search_type => 'time', :keyword => 2.days.ago) %>
  </li>
  <li class="sideButton">
    <%= link_to 'in one week', static_pages_search_path(:search_type => 'time', :keyword => 1.week.ago) %>
  </li>
  <li class="sideButton">
    <%= link_to 'in one month', static_pages_search_path(:search_type => 'time', :keyword => 1.month.ago) %>
  </li>
</ul>


<h4><a href="javascript:showMenu('popTags')">POPULAR TAGS</a></h4>
<ul id="popTags">
  <% tags = get_popular_tags %>
  <% tags.each do |tag| %>
      <li>
        <%= link_to tag[0].to_s + ' (' + tag[1].to_s + ')', static_pages_search_path(:search_type => 'tag', :keyword => tag[0]) %>
      </li>
  <% end %>
</ul>

app/views/layouts/_sidebar_rank.html.erb
<ul class="sidebarRk" id="hottest">
  <h4>Hottest</h4>
    <li class="hotTime">
      <a href="#" onmouseover="easytabs('1', '1');" onfocus="easytabs('1', '1');" onclick="return false;"  title="" id="tablink1">Today</a>
    </li>
    <li class="hotTime">
      <a href="#" onmouseover="easytabs('1', '2');" onfocus="easytabs('1', '2');" onclick="return false;"  title="" id="tablink2">This Week</a>
    </li>
    <li class="hotTime">
      <a href="#" onmouseover="easytabs('1', '3');" onfocus="easytabs('1', '3');" onclick="return false;"  title="" id="tablink3">This Month</a>
    </li>
</ul>

<div id="tabcontent1" class="tabcontent">
  <% @likes = get_hottest('post', 1.day.ago, 10) %>
  <%= render 'layouts/featured_list' %>
</div>

<div id="tabcontent2" class="tabcontent">
  <% @likes = get_hottest('post', 1.week.ago, 10) %>
  <%= render 'layouts/featured_list' %>
</div>

<div id="tabcontent3" class="tabcontent">
  <% @likes = get_hottest('post', 1.month.ago, 10) %>
  <%= render 'layouts/featured_list' %>
</div>

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Admin Panel"
    %link(href="favicon.ico" rel="shortcut icon")

    = stylesheet_link_tag    'admin/admin_ui'
    = javascript_include_tag 'admin/admin_ui'
    = csrf_meta_tags

  %body
    .container
      .row
        .col-md-12
          %h3= content_for?(:title) ? yield(:title) : "Admin Panel"
      .row
        .col-md-3
          = yield :comments_sidebar
        .col-md-9
          = yield :comments_main

    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
    <head>
      <title>JoyCorn</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
      <%= include_gon %>
      <%= favicon_link_tag 'favicon.ico' %>
    </head>
    <body>
        <div id="pagewrap">

          <div id="header">
              <%= render 'layouts/header' %>
          </div>

          <div id="notification">
            <p id="notification-notice" class="notice" data-notice-text="<%= notice %>"><%= notice %></p>
            <p id="notification-alert" class="alert" data-notice-text="<%= alert %>"><%= alert %></p>
          </div>


          <div id="main-panel">
            <!--<div id="floatbox">-->
            <div id="sidebar-wrap" class="sticky">
              <div class="sidebar-classification">
                <%= render 'layouts/sidebar_classification' %>
              </div>
              <div class="sidebar-rank">
                <%= render 'layouts/sidebar_rank' %>
              </div>
            </div>
            <!--</div>-->

              <div id="container" class="home page page-id-367 page-template-default skin-default gecko not-ie query-page query-post sidebar-none">
                <%= yield %>
                <%# params[:current_user] = current_user %>
                <%# debug(params) if Rails.env.development? %>
                <div id="footer">
                  <%= render 'layouts/footer' %>
                </div>
              </div>


          </div>





        </div>

        <%# render 'posts/view' %>



    </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>JoyCorn</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "jQuery-File-Upload/image_upload" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= include_gon %>
</head>
<body>
<h1>Welcome!</h1>

<%= yield %>

<%= link_to 'Go back HOME', root_path %>

</body>